version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile

    container_name: main-app
    ports:
      - "${DJANGO_PORT}:8000"
    command: "sh /entrypoint.sh"
    #    command: gunicorn core.project.wsgi --bind 0.0.0.0:8000
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - ..:/app/